config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Publisher.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Publisher Entity
 *
 * @property int $ID
 * @property string $company_name
 * @property string $contact_fname
 * @property string $contact_sname
 * @property string $pub_street
 * @property string $pub_suburb
 * @property string $pub_state
 * @property string $pub_pc
 * @property string $phone
 * @property string $email
 *
 * @property \App\Model\Entity\Title[] $titles
 */
class Publisher extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'company_name' => true,
        'contact_fname' => true,
        'contact_sname' => true,
        'pub_street' => true,
        'pub_suburb' => true,
        'pub_state' => true,
        'pub_pc' => true,
        'phone' => true,
        'email' => true,
        'titles' => true
    ];

    protected function _getFullName()
    {
        return $this->contact_sname . ', ' . $this->contact_fname;
    }
}

src/Model/Table/PublishersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Publishers Model
 *
 * @property \App\Model\Table\TitlesTable|\Cake\ORM\Association\HasMany $Titles
 *
 * @method \App\Model\Entity\Publisher get($primaryKey, $options = [])
 * @method \App\Model\Entity\Publisher newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Publisher[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Publisher|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Publisher patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Publisher[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Publisher findOrCreate($search, callable $callback = null, $options = [])
 */
class PublishersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('publishers');
        $this->setDisplayField('company_name');
        $this->setPrimaryKey('ID');

        $this->hasMany('Titles', [
            'foreignKey' => 'publisher_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('ID')
            ->allowEmpty('ID', 'create');

        $validator
            ->scalar('company_name')
            ->requirePresence('company_name', 'create')
            ->notEmpty('company_name');

        $validator
            ->scalar('contact_fname')
            ->allowEmpty('contact_fname');

        $validator
            ->scalar('contact_sname')
            ->allowEmpty('contact_sname');

        $validator
            ->scalar('pub_street')
            ->allowEmpty('pub_street');

        $validator
            ->scalar('pub_suburb')
            ->allowEmpty('pub_suburb');

        $validator
            ->scalar('pub_state')
            ->allowEmpty('pub_state');

        $validator
            ->scalar('pub_pc')
            ->allowEmpty('pub_pc');

        $validator
            ->scalar('phone')
            ->allowEmpty('phone');

        $validator
            ->email('email')
            ->allowEmpty('email');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));

        return $rules;
    }
}

src/Controller/PublishersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Publishers Controller
 *
 * @property \App\Model\Table\PublishersTable $Publishers
 *
 * @method \App\Model\Entity\Publisher[] paginate($object = null, array $settings = [])
 */
class PublishersController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $publishers = $this->paginate($this->Publishers);

        $this->set(compact('publishers'));
        $this->set('_serialize', ['publishers']);
    }

    /**
     * View method
     *
     * @param string|null $id Publisher id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $publisher = $this->Publishers->get($id, [
            'contain' => ['Titles']
        ]);

        $this->set('publisher', $publisher);
        $this->set('_serialize', ['publisher']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $publisher = $this->Publishers->newEntity();
        if ($this->request->is('post')) {
            $publisher = $this->Publishers->patchEntity($publisher, $this->request->getData());
            if ($this->Publishers->save($publisher)) {
                $this->Flash->success(__('The publisher has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The publisher could not be saved. Please, try again.'));
        }
        $this->set(compact('publisher'));
        $this->set('_serialize', ['publisher']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Publisher id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $publisher = $this->Publishers->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $publisher = $this->Publishers->patchEntity($publisher, $this->request->getData());
            if ($this->Publishers->save($publisher)) {
                $this->Flash->success(__('The publisher has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The publisher could not be saved. Please, try again.'));
        }
        $this->set(compact('publisher'));
        $this->set('_serialize', ['publisher']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Publisher id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $publisher = $this->Publishers->get($id);
        if ($this->Publishers->delete($publisher)) {
            $this->Flash->success(__('The publisher has been deleted.'));
        } else {
            $this->Flash->error(__('The publisher could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Publishers/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Publishers'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Titles'), ['controller' => 'Titles', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Title'), ['controller' => 'Titles', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="publishers form large-9 medium-8 columns content">
    <?= $this->Form->create($publisher) ?>
    <fieldset>
        <legend><?= __('Add Publisher') ?></legend>
        <?php
            echo $this->Form->control('company_name');
            echo $this->Form->control('contact_fname');
            echo $this->Form->control('contact_sname');
            echo $this->Form->control('pub_street');
            echo $this->Form->control('pub_suburb');
            echo $this->Form->control('pub_state');
            echo $this->Form->control('pub_pc');
            echo $this->Form->control('phone');
            echo $this->Form->control('email');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Publishers/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $publisher->ID],
                ['confirm' => __('Are you sure you want to delete # {0}?', $publisher->ID)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Publishers'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Titles'), ['controller' => 'Titles', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Title'), ['controller' => 'Titles', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="publishers form large-9 medium-8 columns content">
    <?= $this->Form->create($publisher) ?>
    <fieldset>
        <legend><?= __('Edit Publisher') ?></legend>
        <?php
            echo $this->Form->control('company_name');
            echo $this->Form->control('contact_fname');
            echo $this->Form->control('contact_sname');
            echo $this->Form->control('pub_street');
            echo $this->Form->control('pub_suburb');
            echo $this->Form->control('pub_state');
            echo $this->Form->control('pub_pc');
            echo $this->Form->control('phone');
            echo $this->Form->control('email');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Publishers/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Publisher[]|\Cake\Collection\CollectionInterface $publishers
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Publisher'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Titles'), ['controller' => 'Titles', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Title'), ['controller' => 'Titles', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="publishers index large-9 medium-8 columns content">
    <h3><?= __('Publishers') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('ID') ?></th>
                <th scope="col"><?= $this->Paginator->sort('company_name') ?></th>
                <th scope="col"><?= $this->Paginator->sort('contact_fname') ?></th>
                <th scope="col"><?= $this->Paginator->sort('contact_sname') ?></th>
                <th scope="col"><?= $this->Paginator->sort('pub_street') ?></th>
                <th scope="col"><?= $this->Paginator->sort('pub_suburb') ?></th>
                <th scope="col"><?= $this->Paginator->sort('pub_state') ?></th>
                <th scope="col"><?= $this->Paginator->sort('pub_pc') ?></th>
                <th scope="col"><?= $this->Paginator->sort('phone') ?></th>
                <th scope="col"><?= $this->Paginator->sort('email') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($publishers as $publisher): ?>
            <tr>
                <td><?= $this->Number->format($publisher->ID) ?></td>
                <td><?= h($publisher->company_name) ?></td>
                <td><?= h($publisher->full_name) ?></td>
                <td><?= h($publisher->pub_street) ?></td>
                <td><?= h($publisher->pub_suburb) ?></td>
                <td><?= h($publisher->pub_state) ?></td>
                <td><?= h($publisher->pub_pc) ?></td>
                <td><?= h($publisher->phone) ?></td>
                <td><?= h($publisher->email) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $publisher->ID]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $publisher->ID]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $publisher->ID], ['confirm' => __('Are you sure you want to delete # {0}?', $publisher->ID)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

src/Template/Publishers/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Publisher $publisher
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Publisher'), ['action' => 'edit', $publisher->ID]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Publisher'), ['action' => 'delete', $publisher->ID], ['confirm' => __('Are you sure you want to delete # {0}?', $publisher->ID)]) ?> </li>
        <li><?= $this->Html->link(__('List Publishers'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Publisher'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Titles'), ['controller' => 'Titles', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Title'), ['controller' => 'Titles', 'action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="publishers view large-9 medium-8 columns content">
    <h3><?= h($publisher->ID) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('Company Name') ?></th>
            <td><?= h($publisher->company_name) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Contact Fname') ?></th>
            <td><?= h($publisher->contact_fname) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Contact Sname') ?></th>
            <td><?= h($publisher->contact_sname) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Pub Street') ?></th>
            <td><?= h($publisher->pub_street) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Pub Suburb') ?></th>
            <td><?= h($publisher->pub_suburb) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Pub State') ?></th>
            <td><?= h($publisher->pub_state) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Pub Pc') ?></th>
            <td><?= h($publisher->pub_pc) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Phone') ?></th>
            <td><?= h($publisher->phone) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Email') ?></th>
            <td><?= h($publisher->email) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('ID') ?></th>
            <td><?= $this->Number->format($publisher->ID) ?></td>
        </tr>
    </table>
    <div class="related">
        <h4><?= __('Related Titles') ?></h4>
        <?php if (!empty($publisher->titles)): ?>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th scope="col"><?= __('ISBN') ?></th>
                <th scope="col"><?= __('Publisher Id') ?></th>
                <th scope="col"><?= __('Title') ?></th>
                <th scope="col"><?= __('Date Published') ?></th>
                <th scope="col"><?= __('Description') ?></th>
                <th scope="col"><?= __('Topic') ?></th>
                <th scope="col"><?= __('Comments') ?></th>
                <th scope="col"><?= __('Cost Price') ?></th>
                <th scope="col"><?= __('Retail Price') ?></th>
                <th scope="col"><?= __('No In Stock') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($publisher->titles as $titles): ?>
            <tr>
                <td><?= h($titles->ISBN) ?></td>
                <td><?= h($titles->publisher_id) ?></td>
                <td><?= h($titles->title) ?></td>
                <td><?= h($titles->date_published) ?></td>
                <td><?= h($titles->description) ?></td>
                <td><?= h($titles->topic) ?></td>
                <td><?= h($titles->comments) ?></td>
                <td><?= h($titles->cost_price) ?></td>
                <td><?= h($titles->retail_price) ?></td>
                <td><?= h($titles->no_in_stock) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'Titles', 'action' => 'view', $titles->ISBN]) ?>
                    <?= $this->Html->link(__('Edit'), ['controller' => 'Titles', 'action' => 'edit', $titles->ISBN]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['controller' => 'Titles', 'action' => 'delete', $titles->ISBN], ['confirm' => __('Are you sure you want to delete # {0}?', $titles->ISBN)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
</div>